on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  DEVELOPER_DIR: /Applications/Xcode_12.3.app/Contents/Developer

name: Lint
jobs:
  lint:
    name: Lint
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Gem Cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      - name: Bundler
        run: |
            bundle config path vendor/bundle
            bundle install --jobs 4 --retry 3

      - name: Lint
        run: bundle exec pod lib lint --allow-warnings

      - name: Slack Notification
        uses: homoluctus/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: '*iOS SDK Lint*'
          username: 'Github Action: Lint'
          channel: '#apps'
          url: ${{ secrets.SLACK_WEBHOOK }}
