on:
  push:
    branches:    
      - master
name: Lint
jobs:
  test:
    name: Lint
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Lint
        run: pod lib lint --allow-warnings
