on:
  push:
    branches:    
      - master
name: Lint
jobs:
  test:
    name: Lint
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Lint
        run: pod lib lint --allow-warnings
      - name: Notify slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          STATUS: ${{ job.status }}
        uses: pullreminders/slack-action@master
        with:
          args: "{\"channel\":\"CAEE26FV4\",\"text\":\"iOS SDK lint ${STATUS}\"}"